DROP TABLE IF EXISTS CLASS;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
  EMP_NUM INTEGER PRIMARY KEY NOT NULL,
  EMP_LNAME VARCHAR(30) NOT NULL,
  EMP_FNAME VARCHAR(20) NOT NULL
);

CREATE TABLE COURSE (
  CRS_CODE VARCHAR(25) PRIMARY KEY NOT NULL,
  CRS_DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE CLASS (
  CLASS_CODE INTEGER PRIMARY KEY NOT NULL,
  CRS_CODE VARCHAR(25) NOT NULL,
  CLASS_SECTION INTEGER NOT NULL,
  EMP_NUM INTEGER NOT NULL
);

INSERT INTO EMPLOYEE VALUES
  (104, 'Yukon', 'Preston'),
  (228, 'Coronel', 'Carlos');

INSERT INTO COURSE VALUES
  ('WEB-101', 'Web Foundations'),
  ('WEB-202', 'Server Programming'),
  ('DB-110', 'Database Concepts');

INSERT INTO CLASS VALUES
  (1, 'WEB-202', 2, 104),
  (2, 'WEB-101', 1, 104),
  (3, 'DB-110', 1, 228);
