DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
  EMP_NUM INTEGER PRIMARY KEY NOT NULL,
  EMP_LNAME VARCHAR(30) NOT NULL,
  EMP_FNAME VARCHAR(20) NOT NULL
);

CREATE TABLE STUDENT (
  STU_NUM INTEGER PRIMARY KEY NOT NULL,
  STU_LNAME VARCHAR(30) NOT NULL,
  STU_FNAME VARCHAR(20) NOT NULL,
  EMP_NUM INTEGER NOT NULL
);

INSERT INTO EMPLOYEE VALUES
  (10, 'Nguyen', 'Avery'),
  (20, 'Patel', 'Morgan'),
  (30, 'Rivera', 'Jordan');

INSERT INTO STUDENT VALUES
  (1003, 'Zimmer', 'Ana', 20),
  (1001, 'Adams', 'Lee', 10),
  (1004, 'Adams', 'Chris', 30),
  (1002, 'Brown', 'Sam', 10);
