DROP TABLE IF EXISTS ENROLL;
DROP TABLE IF EXISTS CLASS;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS SCHOOL;
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
  EMP_NUM INTEGER PRIMARY KEY NOT NULL,
  EMP_LNAME VARCHAR(30) NOT NULL,
  EMP_FNAME VARCHAR(20) NOT NULL
);
CREATE TABLE SCHOOL (
  SCHOOL_CODE VARCHAR(10) PRIMARY KEY NOT NULL
);
CREATE TABLE DEPARTMENT (
  DEPT_CODE VARCHAR(10) PRIMARY KEY NOT NULL,
  SCHOOL_CODE VARCHAR(10) NOT NULL
);
CREATE TABLE COURSE (
  CRS_CODE VARCHAR(25) PRIMARY KEY NOT NULL,
  DEPT_CODE VARCHAR(10) NOT NULL,
  CRS_DESCRIPTION VARCHAR(255) NOT NULL
);
CREATE TABLE CLASS (
  CLASS_CODE INTEGER PRIMARY KEY NOT NULL,
  CRS_CODE VARCHAR(25) NOT NULL,
  CLASS_SECTION INTEGER NOT NULL,
  EMP_NUM INTEGER NOT NULL
);
CREATE TABLE ENROLL (
  CLASS_CODE INTEGER NOT NULL,
  STU_NUM INTEGER NOT NULL
);

INSERT INTO EMPLOYEE VALUES
  (1, 'Baker', 'Robin'),
  (2, 'Chen', 'Taylor'),
  (3, 'Diaz', 'Alex');
INSERT INTO SCHOOL VALUES ('BUS'), ('ART');
INSERT INTO DEPARTMENT VALUES ('ACCT', 'BUS'), ('CIS', 'BUS'), ('DES', 'ART');
INSERT INTO COURSE VALUES
  ('ACCT-1', 'ACCT', 'Accounting Basics'),
  ('CIS-2', 'CIS', 'Business Systems'),
  ('DES-3', 'DES', 'Design Studio');
INSERT INTO CLASS VALUES
  (101, 'CIS-2', 2, 2),
  (102, 'ACCT-1', 1, 1),
  (103, 'DES-3', 1, 3);
INSERT INTO ENROLL VALUES
  (101, 10), (101, 11), (101, 12),
  (102, 20),
  (103, 30), (103, 31), (103, 32), (103, 33);
